#! /bin/bash
# Show a list of many possible imfuse backgrounds.
# Provide stack images as arguments

imfuse -V --background=enfuse "$@"
imfuse -V --background=saturation "$@"
imfuse -V --background=mean "$@"
imfuse -V --cache --background=max "$@"
imfuse -V --cache --background=min "$@"
Compose1list="
blend difference dividesrc exclusion hardmix interpolate
linearburn lineardodge minusdst modulusadd multiply 
negate plus screen"
Compose2list="
bumpmap colorburn colordodge colorize displace distort  
freeze hardlight linearlight modulate modulussubstract 
overlay pegtoplight pinlight reflect saturate 
softburn softdodge softlight stamp vividlight
"
for Composemode in $Compose1list $Compose2list; do
  imfuse -V --cache --background=${Composemode} "$@"
done
for Composemode in $Compose2list; do
  imfuse -V --cache --background=${Composemode}2 "$@"
done

# out of curiosity: mean image of all interesting background results
imfuse -V --output=background-mean-allmodes.tif --background=mean imfuse.bg*

# mean image of all background images that preserve the background color
Truecolormodes="enfuse
saturation
max
mean
min
colorize
colorize2
pinlight
pinlight2
"
for Mode in $Truecolormodes; do
  List="$List imfuse.bg=$Mode.*"
done
eval imfuse -V --background=mean --output=background-mean-truecolormodes.tif $List
