#! /bin/bash
  
##  Laplacian Edge Detection
# Enfuse provides a Laplacian-based algorithm that can help in situations where weighting based on the standard deviation fails. 
# It is activated with a positive value for SCALE in --contrast-edge-scale=SCALE. 
# The Laplacian will detect two-dimensional curvature on the scale of SCALE. 
# Here and in the following we simply speak of curvature where we mean magnitude of curvature. 
# That is, we shall not distinguish between convex and concave edges. Enfuse always use the magnitude of curvature for weighting.
#
# Typically, SCALE ranges between 0.1 pixels and 0.5 pixels, where 0.3 pixels are a reasonable starting point. 
# To find the best value for SCALE though, usually some experimentation will be necessary. 
# Use --save-masks to get all soft-mask (default: softmask-%n.tif) and hard-mask files (default: hardmask-%n.tif). Check how different scales affect the artifacts. 
#
## Local Contrast Enhancement
# Sometimes Enfuse misses smoother edges with --contrast-edge-scale and a little local contrast enhancement (LCE) helps. 
# Set --contrast-edge-scale=SCALE:LCE-SCALE:LCE-FACTOR, 
# where LCE-SCALE and LCE-FACTOR work like the unsharp mask filters in various image manipulation programs. 
# Start with LCE-SCALE ten times the value of SCALE and a LCE-FACTOR of 2-5.
#
# LCE-SCALE can be specified as a percentage of SCALE. LCE-FACTOR also can be specified as a percentage. 
# Examples:
#    --contrast-edge-scale=0.3:3.0:3
#    --contrast-edge-scale=0.3:1000%:3.0
#    --contrast-edge-scale=0.3:3:300%
#    --contrast-edge-scale=0.3:1000%:300% 

# --exposure-weight-function=gaussian
# one of the built-in exposure WEIGHT-FUNCTIONs: "gaussian", "lorentzian", "half-sine", "full-sine", or "bi-square"; default: "gaussian"

# --exposure-optimum=0.5
# optimum  exposure  value, usually the maximum of the weighting function (0 <= OPTIMUM <= 1); default: 0.5
#Exposureoptimum=0.5
#    --exposure-optimum=$Exposureoptimum \

# --contrast-window-size=SIZE
#   set window SIZE for local-contrast analysis (SIZE >= 3); default: 5
#   Does not take effect if --contrast-edge-scale is in use.
#Contrastwindowsize=5
#    --contrast-window-size=$Contrastwindowsize \



#      --gray-projector=l-star \
#    --contrast-window-size=$Contrastsize \


Stackdir="$1"
Stackdir="$(realpath "$Stackdir")"
[ -d "$Stackdir" ] || {
  echo "Stackverzeichnis $Stackdir nicht gefunden"
}
cd $Stackdir

Fusedir=$Stackdir/fuse
mkdir $Fusedir

#########
#cd $Fusedir
#while read Line; do
#  New="$Line"
#  New="$(sed 's/ContES:0.5:1000%:5.jpg/ContES:0.5:1000%:1000%.jpg/' <<< "$New")"
#  New="$(sed 's/ContES:0.3:1000%:3.jpg/ContES:0.3:1000%:1000%.jpg/' <<< "$New")"
#  New="$(sed 's/ContES:0.2:1000%:2.jpg/ContES:0.2:1000%:1000%.jpg/' <<< "$New")"
#  New="$(sed 's/ContW:0_/ContW:0.0_/' <<< "$New")"
#  New="$(sed 's/ExpW:0_/ExpW:0.0_/' <<< "$New")"
#  New="$(sed 's/SatW:0_/SatW:0.0_/' <<< "$New")"
#  New="$(sed 's/ContW:1_/ContW:1.0_/' <<< "$New")"
#  New="$(sed 's/ExpW:1_/ExpW:1.0_/' <<< "$New")"
#  New="$(sed 's/SatW:1_/SatW:1.0_/' <<< "$New")"
#  [ "$Line" = "$New" ] || {
#    echo $Line
#    echo $New
##    mv "$Line" "$New"
#  }  
#done < <(find fuse*)
#exit

#########

goodset() {
  Exposureweight="0.0"
  Saturationweight="0.0"
  Contrastweight="0.0"
  Scale="0.0"
  Lcescale="0.0"
  Lcefactor="0.0"
  case $1 in
    1) # *
      Contrastweight="1.0"
    ;;
    2) 
      Contrastweight="1.0"
      Scale="0.3"
      Lcescale="300%"
      Lcefactor="300%"
    ;;
    3) 
      Contrastweight="1.0"
      Scale="0.3"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    4) 
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    6) 
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    7) # **
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="1000%"
    ;;
    8) 
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="2000%"
    ;;
    9) # **
      Contrastweight="1.0"
      Scale="0.8"
      Lcescale="1000%"
      Lcefactor="1000%"
    ;;
    10) # **
      Contrastweight="1.0"
      Scale="0.8"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    11) 
      Contrastweight="1.0"
      Scale="0.8"
      Lcescale="1000%"
      Lcefactor="2000%"
    ;;
    12) 
      Contrastweight="1.0"
      Scale="0.8"
      Lcescale="500%"
      Lcefactor="1000%"
    ;;
    
    15)
      Exposureweight="1.0"
    ;;
    16) # ***
      Exposureweight="0.3"
    ;;
    17)
      Exposureweight="1.0"
      Saturationweight="0.2"
    ;;
    18) # ***
      Exposureweight="0.3"
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    19) 
      Exposureweight="0.3"
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
      Grayprojector="luminance"
    ;;
    
    20) # ***
      Saturationweight="0.3"
    ;;
    21)
      Saturationweight="1.0"
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    22)
      Saturationweight="0.3"
      Contrastweight="1.0"
      Scale="1.0"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    
    30) 
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="0.5"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    31) 
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="0.5"
      Scale="1.0"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    32) 
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="0.5"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
      Grayprojector="luminance"
    ;;
    36) # ***
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="1.0"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    37)
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="0.5"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="300%"
    ;;
    37)
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="0.5"
      Scale="0.5"
      Lcescale="1000%"
      Lcefactor="1000%"
    ;;
    
    41) # *** phako
      Exposureweight="0.3"
      Saturationweight="0.3"
      Contrastweight="1.0"
      Scale="1.0"
      Lcescale="1000%"
      Lcefactor="2000%"
    ;;
    *) return 1 ;;
  esac
}

fuse() {
  Enfuseoptions=" \
    --exposure-weight=$Exposureweight \
    --saturation-weight=$Saturationweight \
    --contrast-weight=$Contrastweight"
  Commandnote="ExpW:${Exposureweight}_SatW:${Saturationweight}_ContW:${Contrastweight}"
  [ "$Contrastweight" != "0.0" ] && [ "$Scale" != "0.0" ] && {
    Commandnote="${Commandnote}_ContES:${Scale}:${Lcescale}:${Lcefactor}"
    Enfuseoptions="$Enfuseoptions \
      --contrast-edge-scale=$Scale:$Lcescale:$Lcefactor"
  }
  [ "$Grayprojector" = "average" ] || {
    { [ "$Contrastweight" = "0.0" ] && [ "$Exposureweight" = "0.0" ] ; } || {
      Commandnote="${Commandnote}_GrayP:$Grayprojector"
      Enfuseoptions="$Enfuseoptions \
        --gray-projector=$Grayprojector"
    }
  }
  [ "$Mask" = "--soft-mask" ] && Commandnote="${Commandnote}_soft"
  [ "$Contrastmincurvature" ] && {
    Enfuseoptions="$Enfuseoptions \
        --contrast-min-curvature=$Contrastmincurvature"
    Commandnote="${Commandnote}_Curv:$Contrastmincurvature"
  }
              
  Fusefilename="fuse_$Commandnote.jpg"
  echo "Bild $Count von $Anzahl: $Fusefilename"
  echo "Verzeichnis: $Fusedir"
  pwd
  [ -e "$Fusedir/$Fusefilename" ] || enfuse \
    $Enfuseoptions \
    --output="$Fusedir/$Fusefilename" \
    --verbose=0 \
    preview*.jpg 2>&1 | grep -v "assuming all pixels should contribute to the final image" | grep -v "does not have an alpha channel"

  Imagelist="$Imagelist -label $Commandnote $Fusedir/$Fusefilename"
}

fuse_array() {
  #Exposureweightarray=("0" "0.1" "0.2" "0.3" "0.4" "0.5" "0.6" "0.7" "0.8" "0.9" "1")
  Exposureweightarray=("0.0" "0.3" "0.7")
  #Saturationweightarray=("0" "0.1" "0.2" "0.3" "0.4" "0.5" "0.6" "0.7" "0.8" "0.9" "1")
  Saturationweightarray=("0.0" "0.3" "0.7")
  #Contrastweightarray=("0" "0.1" "0.2" "0.3" "0.4" "0.5" "0.6" "0.7" "0.8" "0.9" "1")
  Contrastweightarray=("0.0" "0.5" "1.0")
  #Scalearray=("0.1" "0.2" "0.3" "0.4" "0.5")
  Scalearray=("0.5")
  Lcescalearray=("1000%")
  #Lcefactorarray=("2" "3" "4" "5")
  Lcefactorarray=("1000%")
  Grayprojectorarray=("average" "l-star" "luminance" "value" "anti-value")
  #Maskarray=("--hard-mask" "--soft-mask")
  Maskarray=("--hard-mask")

  Anzahl=$(bc <<< "${#Exposureweightarray[*]} * ${#Saturationweightarray[*]} * ${#Contrastweightarray[*]} * ${#Scalearray[*]} * ${#Lcescalearray[*]} * ${#Lcefactorarray[*]} * ${#Grayprojectorarray[*]} * ${#Maskarray[*]}")
  Count=0
  Zeilenanzahl=0
  
  for Scale in ${Scalearray[@]} ; do
    for Lcescale in ${Lcescalearray[@]} ; do
      for Lcefactor in ${Lcefactorarray[@]} ; do
        for Grayprojector in ${Grayprojectorarray[@]} ; do
          for Mask in ${Maskarray[@]} ; do
          Zeilenanzahl=$((Zeilenanzahl+1))
            for Exposureweight in ${Exposureweightarray[@]} ; do
              for Saturationweight in ${Saturationweightarray[@]} ; do
                for Contrastweight in ${Contrastweightarray[@]} ; do
                    Count=$((Count +1))
                    fuse
              
                    # Fortschrittsanzeige %
                    for ((i=1 ; i<=100 ; i++)); do
                      Prozent="$((100 * $Count / $Anzahl))"
                      [ "$Prozent" -lt "$i" ] && echo -n "." || echo -n "X" 
                    done
                    echo " $Prozent%"
            
                done
              done
            done
          done
        done
      done
    done
  done

  # Übersichtsabelle
  echo "Übersichtstabelle wird angelegt"
  montage -geometry '+5+5' -pointsize 24 -tile $(($Anzahl / $Zeilenanzahl ))x${Zeilenanzahl} $Imagelist $Fusedir/array_fuse.jpg
  echo "*** FERTIG ***"
}

fuse_selection() {
  for ((i=1 ; i<=1000 ; i++)); do
  
    Grayprojector="average"
    Contrastmincurvature=""
    goodset $i && fuse
    #Contrastmincurvature="0.5%"
    #goodset $i && fuse
    #Contrastmincurvature="-0.5%"
    #goodset $i && fuse
  done
  montage -geometry '+5+5' -pointsize 20 $Imagelist $Fusedir/auswahl_fuse.jpg
  echo FERTIG
}

fuse_selection
