#! /bin/bash

kaptaingrammar() {
  echo "#! /usr/bin/kaptain
start 'imgview' -> imgname identify imgview @fill;
  imgname  -> @text='' ;
  identify -> @text='' ;
  imgview  -> @icon='' ;
"
}
sendkaptain() {
  # send messages to kaptain over its stdin
  echo "${1:-}" >>${Kaptainstdinfile}
}
pipekaptain() {
  # provide script for interactive kaptain option --pipe
  # Needs containing variables to be set beforehand.
  echo  "#! /bin/bash
tail -f ${Kaptainstdinfile} & Tailpid=\$!
cat >> ${Kaptainstdoutfile}
kill \$Tailpid
" >$Kaptainpipefile
  chmod +x $Kaptainpipefile
}
runkaptain() {
  # start kaptain
  kaptaingrammar >"$Kaptaingrammarfile"
  :>     "$Kaptainstdinfile"
  :>     "$Kaptainstdoutfile"
  
  pipekaptain
  tail --pid=$$ -f "$Kaptainstdoutfile" >> $Kaptainanswerfile &
  
  kaptain --pipe $Kaptainpipefile $Kaptaingrammarfile & Kaptainpid=$!
  echo "$Kaptainpid" > "$Kaptainpidfile"
}
main() {
  local Showimage Cachedir
  local Kaptaingrammarfile Kaptainstdinfile Kaptainstdoutfile Kaptainanswerfile Kaptainpipefile 
  local Kaptainpidfile Kaptainpid
  
  Showimage="${1:-}"
  Cachedir="/tmp/imgview"
  
  Kaptaingrammarfile="$Cachedir/gui_main.kaptain.grammar"
  Kaptainstdinfile="$Cachedir/gui_main.kaptain.stdin" 
  Kaptainstdoutfile="$Cachedir/gui_main.kaptain.stdout"
  Kaptainanswerfile="$Cachedir/gui_main.kaptain.reply"
  Kaptainpipefile="$Cachedir/gui_main.kaptain.pipe.sh"
  Kaptainpidfile="$Cachedir/kaptain.pid"
  
  mkdir -p "$Cachedir"
  Kaptainpid="$(cat "$Kaptainpidfile")"

  ps -p "$Kaptainpid" >/dev/null || runkaptain
  
  sendkaptain "imgname='$(basename "$Showimage")'"
  sendkaptain "identify='$(identify -format '%m %wx%h %qbit %r %b' "$Showimage")'"
  sendkaptain "imgview('$Showimage')=''"
}

[ -f "${1:-}" ] || {
  echo "imgview
Simple image viewer that allows remote content refresh
without window flickering and without blocking the terminal.

Usage:
  imgview IMAGE
  
Dependencies: kaptain, imagemagick"
  exit
}
main "$@"
